/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.apache.tomcat.jni.Library;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
